export type RarityKind = 'legendary' | 'mythical'

// Lista estática verificada contra pokemon-species (is_legendary/is_mythical)
// para las 1025 especies actuales, generada una única vez. Se usa solo en la
// GRILLA, donde no pedimos el detalle completo por card (para no volver al
// problema de N+1 fetch que ya resolvimos con useTypeIndex). En la ficha de
// detalle no hace falta esta lista: ahí ya tenemos species.is_legendary /
// is_mythical directo, sin costo extra.
//
// Si en el futuro sale una nueva generación con nuevos legendarios/míticos,
// hay que regenerar esta lista (no se actualiza sola).
export const LEGENDARY_POKEMON: Record<string, RarityKind> = {
  articuno: 'legendary',
  zapdos: 'legendary',
  moltres: 'legendary',
  mewtwo: 'legendary',
  mew: 'mythical',
  raikou: 'legendary',
  entei: 'legendary',
  suicune: 'legendary',
  lugia: 'legendary',
  'ho-oh': 'legendary',
  celebi: 'mythical',
  regirock: 'legendary',
  regice: 'legendary',
  registeel: 'legendary',
  latias: 'legendary',
  latios: 'legendary',
  kyogre: 'legendary',
  groudon: 'legendary',
  rayquaza: 'legendary',
  jirachi: 'mythical',
  deoxys: 'mythical',
  uxie: 'legendary',
  mesprit: 'legendary',
  azelf: 'legendary',
  dialga: 'legendary',
  palkia: 'legendary',
  heatran: 'legendary',
  regigigas: 'legendary',
  giratina: 'legendary',
  cresselia: 'legendary',
  phione: 'mythical',
  manaphy: 'mythical',
  darkrai: 'mythical',
  shaymin: 'mythical',
  arceus: 'mythical',
  victini: 'mythical',
  cobalion: 'legendary',
  terrakion: 'legendary',
  virizion: 'legendary',
  tornadus: 'legendary',
  thundurus: 'legendary',
  reshiram: 'legendary',
  zekrom: 'legendary',
  landorus: 'legendary',
  kyurem: 'legendary',
  keldeo: 'mythical',
  meloetta: 'mythical',
  genesect: 'mythical',
  xerneas: 'legendary',
  yveltal: 'legendary',
  zygarde: 'legendary',
  diancie: 'mythical',
  hoopa: 'mythical',
  volcanion: 'mythical',
  'type-null': 'legendary',
  silvally: 'legendary',
  'tapu-koko': 'legendary',
  'tapu-lele': 'legendary',
  'tapu-bulu': 'legendary',
  'tapu-fini': 'legendary',
  cosmog: 'legendary',
  cosmoem: 'legendary',
  solgaleo: 'legendary',
  lunala: 'legendary',
  necrozma: 'legendary',
  magearna: 'mythical',
  marshadow: 'mythical',
  zeraora: 'mythical',
  meltan: 'mythical',
  melmetal: 'mythical',
  zacian: 'legendary',
  zamazenta: 'legendary',
  eternatus: 'legendary',
  kubfu: 'legendary',
  urshifu: 'legendary',
  zarude: 'mythical',
  regieleki: 'legendary',
  regidrago: 'legendary',
  glastrier: 'legendary',
  spectrier: 'legendary',
  calyrex: 'legendary',
  enamorus: 'legendary',
  'wo-chien': 'legendary',
  'chien-pao': 'legendary',
  'ting-lu': 'legendary',
  'chi-yu': 'legendary',
  koraidon: 'legendary',
  miraidon: 'legendary',
  okidogi: 'legendary',
  munkidori: 'legendary',
  fezandipiti: 'legendary',
  ogerpon: 'legendary',
  terapagos: 'legendary',
  pecharunt: 'mythical',
}

export function getRarity(name: string): RarityKind | null {
  return LEGENDARY_POKEMON[name] ?? null
}
